---
language: python
python: "2.7"
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Perform a test run with the playbook
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Perform a another test run with the playbook to check for idempotency
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -qP 'changed=0.*failed=0'
    && (echo "Idempotence: PASS"; exit 0)
    || (echo "Idempotence: FAIL"; exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
