---
- name: Remove ZFS modprobe configuration
  file:
    dest: /etc/modprobe.d/zfs.conf
    state: absent
  when: >
    (pve_zfs_options is not defined) or
    (pve_zfs_options is defined and not pve_zfs_options) or
    (not pve_zfs_enabled)

- name: Disable loading of ZFS module on init
  file:
    dest: /etc/modules-load.d/zfs.conf
    state: absent
  when: not pve_zfs_enabled
