---
- name: Gather distribution specific variables
  include_vars: "debian-{{ ansible_distribution_release }}.yml"

- name: Calculate list of SSH addresses
  set_fact:
    pve_cluster_ssh_addrs: >-
      ["{{ ansible_fqdn }}", "{{ ansible_hostname }}",
      "{{ pve_cluster_addr0 }}",
      {% if pve_cluster_addr1 is defined %}"{{ pve_cluster_addr1 }}"{% endif %}]
