---
# tasks file for ansible-role-proxmox
- include: ssh_cluster_config.yml

- name: Ensure public IP is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    regexp: "{{ ansible_hostname }}"

- name: Trust Proxmox' packaging key
  apt_key:
    keyserver: pgp.mit.edu
    id: 9887F95A
    state: present

- name: Add Proxmox repository
  apt_repository:
    repo: "{{ proxmox_repository_line }}"
    filename: proxmox
    state: present

- name: Run dist-upgrade
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install Proxmox VE and related packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - proxmox-ve
    - postfix
    - open-iscsi
    - ksm-control-daemon
    - systemd-sysv
    - patch

- block:

  - name: Remove automatically installed PVE Enterprise repo configuration
    apt_repository:
      repo: "deb https://enterprise.proxmox.com/debian jessie pve-enterprise"
      filename: pve-enterprise
      state: absent

  - name: Remove subscription check wrapper function in web UI
    patch:
      src: 00_remove_checked_command.patch
      dest: /usr/share/pve-manager/ext6/pvemanagerlib.js
      backup: yes

  when: "'pve-no-subscription' in proxmox_repository_line"

- name: Check if kernel has been updated
  script: scripts/check_kernel_update.sh
  register: __proxmox_kernel
  changed_when: "__proxmox_kernel.stdout == 'updated=true'"
  when: proxmox_check_for_kernel_update

- block:

  - name: Reboot for kernel update
    command: "shutdown -r +1 'PVE kernel update detected by Ansible, rebooting'"
    async: 0
    poll: 0
    ignore_errors: true

  - name: Wait for server to come back online
    local_action: wait_for port=22 host={{ inventory_hostname }} search_regex=OpenSSH delay=60 timeout=450
    become: false

  when:
    - proxmox_reboot_on_kernel_update
    - __proxmox_kernel | changed

- name: Remove old Debian kernels
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - linux-image-amd64
    - linux-image-3.16.0-4-amd64
  when:
    - proxmox_remove_old_kernels
    - not __proxmox_kernel | changed

- name: LDAP fix for authenticated search
  lineinfile:
    line: "    $ldap->bind('{{ proxmox_ldap_bind_user }}', password => '{{ proxmox_ldap_bind_password }}');"
    insertbefore: "ldap->search\\("
    dest: /usr/share/perl5/PVE/Auth/LDAP.pm
  notify:
    - restart pvedaemon
  when:
    - proxmox_ldap_bind_user is defined
    - proxmox_ldap_bind_password is defined

