---
- name: Generate new cryptographic key for corosync
  command: "corosync-keygen -l -k {{ pve_cluster_authfile }}"
  args:
    creates: "{{ pve_cluster_authfile }}"

- name: Query cluster.status
  proxmox_query:
    name: cluster.status
  register: __pve_cluster

- set_fact:
    __pve_in_cluster: '{{ __pve_cluster.response | json_query(query) }}'
  when: "__pve_cluster.response | json_query(query) | ternary(true, false)"
  vars:
    query: "[?type='cluster'].name"

- set_fact:
    __pve_clusters: "{{ __pve_clusters | default([]) | intersect([hostvars[item]['__pve_in_cluster']]) }}"
  when: "'__pve_in_cluster' in hostvars[item]"
  with_items: "{{ groups[pve_group] }}"

- assert:
    that:
      - "(__pve_clusters | default([]) | length) <= 1"
    msg: "Some or all of the hosts in {{ pve_group }} appear to already be part of two or more different clusters, please ensure groups only have hosts meant to be in one single cluster."

- assert:
    that:
      - "__pve_clusters[0] == pve_cluster_clustername"
    msg: "Some or all of the hosts in group '{{ pve_group }}' appear to be in a cluster named '{{ __pve_clusters[0] }}', which differs from the specified clustername of '{{ pve_cluster_clustername }}'. Please ensure the clustername is correct. The existing cluster's name cannot be modified."
  when: "(__pve_clusters | default([]) | length) == 1"

- name: Initialize the Proxmox cluster
  command: "pvecm create {{ pve_cluster_clustername }} -bindnet0_addr {{ pve_cluster_bindnet0_addr }} -ring0_addr {{ pve_cluster_ring0_addr }}{% if pve_cluster_bindnet1_addr is defined and pve_cluster_ring1_addr is defined %} -bindnet1_addr {{ pve_cluster_bindnet1_addr }} -ring1_addr {{ pve_cluster_ring1_addr }}{% endif %}"
  args:
    creates: "{{ pve_cluster_conf }}"
  when:
    - "__pve_clusters is not defined"
    - "inventory_hostname == groups[pve_group][0]"

- name: Add node to Proxmox cluster
  command: "pvecm add {{ hostvars[groups[pve_group][0]]['ansible_default_ipv4']['address'] }} -ring0_addr {{ pve_cluster_ring0_addr }}{% if pve_cluster_ring1_addr is defined %} -ring1_addr {{ pve_cluster_ring1_addr }}{% endif %}"
  args:
    creates: "{{ pve_cluster_conf }}"
  when:
    - "__pve_in_cluster is not defined"
    - "inventory_hostname != groups[pve_group][0]"
