---
- name: Create SSH directory for root
  file:
    path: /root/.ssh/
    state: directory
    mode: 0700

- name: Create root SSH key pair for PVE
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: /root/.ssh/id_rsa
    ssh_key_type: rsa
    ssh_key_comment: "root@{{ inventory_hostname_short }}"

- name: Fetch root SSH public key
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: "{{ pve_fetch_directory }}/{{ inventory_hostname }}/root_rsa.pub"
    fail_on_missing: yes
    flat: yes

- name: Authorize all hosts' root SSH public keys
  authorized_key:
    user: root
    key: "{{ lookup('file', pve_fetch_directory + '/' + item + '/root_rsa.pub') }}"
  with_items: "{{ groups[pve_group] }}"

- name: Add key configuration for accessing PVE hosts
  blockinfile:
    dest: /root/.ssh/config
    marker: "# {mark} {{ item }}"
    content: |
      Host {{ item }} {{ hostvars[item].ansible_default_ipv4.address }}
          IdentityFile /root/.ssh/id_rsa
    create: yes
  with_items: "{{ groups[pve_group] }}"

- name: Allow root logins from cluster hosts
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} Allow {{ item }} to login as root"
    content: |
      Match Address {{ hostvars[item].ansible_default_ipv4.address }}
          PermitRootLogin yes
    validate: "/usr/sbin/sshd -t -f %s"
  with_items: "{{ groups[pve_group] }}"
  notify:
    - reload sshd configuration

- name: Fetch SSH public host keys
  fetch:
    src: "/etc/ssh/{{ item }}"
    dest: "{{ pve_fetch_directory }}/{{ inventory_hostname }}/{{ item }}"
    flat: yes
  with_items:
    - ssh_host_rsa_key.pub
    - ssh_host_ed25519_key.pub
    - ssh_host_ecdsa_key.pub

- name: Add every host's host keys to global known_hosts
  blockinfile:
    dest: "/etc/ssh/ssh_known_hosts"
    marker: "# {mark} PROXMOX HOST KEYS (ANSIBLE MANAGED)"
    content: |
      {% for host in groups[pve_group] %}
      {% for keytype in ['rsa', 'ed25519', 'ecdsa'] %}
      {{ hostvars[host].ansible_default_ipv4.address }},{{ hostvars[host].ansible_fqdn }},{{ hostvars[host].ansible_hostname }} {{ ' '.join(lookup('file', pve_fetch_directory + '/' + host + '/ssh_host_' + keytype + '_key.pub').split()[:-1]) }}
      {% endfor %}
      {% endfor %}
    create: yes
