---
# handlers file for ansible-role-proxmox
- name: restart pvedaemon
  service:
    name: pvedaemon
    state: restarted

- name: reload sshd configuration
  service:
    name: sshd
    state: reloaded

- name: reload watchdog-mux
  service:
    name: watchdog-mux
    state: restarted
