---
# handlers file for ansible-role-proxmox
- name: restart pvedaemon
  service:
    name: pvedaemon
    state: restarted

- name: restart pveproxy
  service:
    name: pveproxy
    state: restarted

- name: reload sshd configuration
  service:
    name: sshd
    state: reloaded

- name: restart watchdog-mux
  service:
    name: watchdog-mux
    state: restarted

- name: restart zfs-zed
  service:
    name: zfs-zed
    state: restarted
